//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18034
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cerberus.ATC.GatewayV2Service.wsParametricas {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CEModulos", Namespace="http://schemas.datacontract.org/2004/07/ExternosNegociosCoreSoat.Modulos.ClasesBa" +
        "se")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Cerberus.ATC.GatewayV2Service.wsParametricas.CEPar))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Cerberus.ATC.GatewayV2Service.wsParametricas.CEParObtenerVehiculoTipos))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Cerberus.ATC.GatewayV2Service.wsParametricas.CEParObtenerVehiculoUsos))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Cerberus.ATC.GatewayV2Service.wsParametricas.CEParObtenerDepartamentos))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Cerberus.ATC.GatewayV2Service.wsParametricas.CEParObtenerFacturaTipo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Cerberus.ATC.GatewayV2Service.wsParametricas.CEParObtenerGestion))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Cerberus.ATC.GatewayV2Service.wsParametricas.CEParObtenerMedioPago))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Cerberus.ATC.GatewayV2Service.wsParametricas.CEParObtenerVentaCanal))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Cerberus.ATC.GatewayV2Service.wsParametricas.CEParObtenerBancos))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Cerberus.ATC.GatewayV2Service.wsParametricas.CEParObtenerPlacasTipo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Cerberus.ATC.GatewayV2Service.wsParametricas.CEParObtenerPrimas))]
    public partial class CEModulos : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SoatTIntermediarioFkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SoatTIntermediarioFk {
            get {
                return this.SoatTIntermediarioFkField;
            }
            set {
                if ((this.SoatTIntermediarioFkField.Equals(value) != true)) {
                    this.SoatTIntermediarioFkField = value;
                    this.RaisePropertyChanged("SoatTIntermediarioFk");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usuario {
            get {
                return this.UsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioField, value) != true)) {
                    this.UsuarioField = value;
                    this.RaisePropertyChanged("Usuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CEPar", Namespace="http://schemas.datacontract.org/2004/07/ExternosNegociosCoreSoat.Modulos.Parametr" +
        "icas.ClasesEntrada")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Cerberus.ATC.GatewayV2Service.wsParametricas.CEParObtenerVehiculoTipos))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Cerberus.ATC.GatewayV2Service.wsParametricas.CEParObtenerVehiculoUsos))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Cerberus.ATC.GatewayV2Service.wsParametricas.CEParObtenerDepartamentos))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Cerberus.ATC.GatewayV2Service.wsParametricas.CEParObtenerFacturaTipo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Cerberus.ATC.GatewayV2Service.wsParametricas.CEParObtenerGestion))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Cerberus.ATC.GatewayV2Service.wsParametricas.CEParObtenerMedioPago))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Cerberus.ATC.GatewayV2Service.wsParametricas.CEParObtenerVentaCanal))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Cerberus.ATC.GatewayV2Service.wsParametricas.CEParObtenerBancos))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Cerberus.ATC.GatewayV2Service.wsParametricas.CEParObtenerPlacasTipo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Cerberus.ATC.GatewayV2Service.wsParametricas.CEParObtenerPrimas))]
    public partial class CEPar : Cerberus.ATC.GatewayV2Service.wsParametricas.CEModulos {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SeguridadTokenField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SeguridadToken {
            get {
                return this.SeguridadTokenField;
            }
            set {
                if ((this.SeguridadTokenField.Equals(value) != true)) {
                    this.SeguridadTokenField = value;
                    this.RaisePropertyChanged("SeguridadToken");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CEParObtenerVehiculoTipos", Namespace="http://schemas.datacontract.org/2004/07/ExternosNegociosCoreSoat.Modulos.Parametr" +
        "icas.ClasesEntrada")]
    [System.SerializableAttribute()]
    public partial class CEParObtenerVehiculoTipos : Cerberus.ATC.GatewayV2Service.wsParametricas.CEPar {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CEParObtenerVehiculoUsos", Namespace="http://schemas.datacontract.org/2004/07/ExternosNegociosCoreSoat.Modulos.Parametr" +
        "icas.ClasesEntrada")]
    [System.SerializableAttribute()]
    public partial class CEParObtenerVehiculoUsos : Cerberus.ATC.GatewayV2Service.wsParametricas.CEPar {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CEParObtenerDepartamentos", Namespace="http://schemas.datacontract.org/2004/07/ExternosNegociosCoreSoat.Modulos.Parametr" +
        "icas.ClasesEntrada")]
    [System.SerializableAttribute()]
    public partial class CEParObtenerDepartamentos : Cerberus.ATC.GatewayV2Service.wsParametricas.CEPar {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CEParObtenerFacturaTipo", Namespace="http://schemas.datacontract.org/2004/07/ExternosNegociosCoreSoat.Modulos.Parametr" +
        "icas.ClasesEntrada")]
    [System.SerializableAttribute()]
    public partial class CEParObtenerFacturaTipo : Cerberus.ATC.GatewayV2Service.wsParametricas.CEPar {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CEParObtenerGestion", Namespace="http://schemas.datacontract.org/2004/07/ExternosNegociosCoreSoat.Modulos.Parametr" +
        "icas.ClasesEntrada")]
    [System.SerializableAttribute()]
    public partial class CEParObtenerGestion : Cerberus.ATC.GatewayV2Service.wsParametricas.CEPar {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CEParObtenerMedioPago", Namespace="http://schemas.datacontract.org/2004/07/ExternosNegociosCoreSoat.Modulos.Parametr" +
        "icas.ClasesEntrada")]
    [System.SerializableAttribute()]
    public partial class CEParObtenerMedioPago : Cerberus.ATC.GatewayV2Service.wsParametricas.CEPar {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CEParObtenerVentaCanal", Namespace="http://schemas.datacontract.org/2004/07/ExternosNegociosCoreSoat.Modulos.Parametr" +
        "icas.ClasesEntrada")]
    [System.SerializableAttribute()]
    public partial class CEParObtenerVentaCanal : Cerberus.ATC.GatewayV2Service.wsParametricas.CEPar {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CEParObtenerBancos", Namespace="http://schemas.datacontract.org/2004/07/ExternosNegociosCoreSoat.Modulos.Parametr" +
        "icas.ClasesEntrada")]
    [System.SerializableAttribute()]
    public partial class CEParObtenerBancos : Cerberus.ATC.GatewayV2Service.wsParametricas.CEPar {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CEParObtenerPlacasTipo", Namespace="http://schemas.datacontract.org/2004/07/ExternosNegociosCoreSoat.Modulos.Parametr" +
        "icas.ClasesEntrada")]
    [System.SerializableAttribute()]
    public partial class CEParObtenerPlacasTipo : Cerberus.ATC.GatewayV2Service.wsParametricas.CEPar {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CEParObtenerPrimas", Namespace="http://schemas.datacontract.org/2004/07/ExternosNegociosCoreSoat.Modulos.Parametr" +
        "icas.ClasesEntrada")]
    [System.SerializableAttribute()]
    public partial class CEParObtenerPrimas : Cerberus.ATC.GatewayV2Service.wsParametricas.CEPar {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ParGestionFkField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ParGestionFk {
            get {
                return this.ParGestionFkField;
            }
            set {
                if ((this.ParGestionFkField.Equals(value) != true)) {
                    this.ParGestionFkField = value;
                    this.RaisePropertyChanged("ParGestionFk");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CSModulos", Namespace="http://schemas.datacontract.org/2004/07/ExternosNegociosCoreSoat.Modulos.ClasesBa" +
        "se")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Cerberus.ATC.GatewayV2Service.wsParametricas.CSPar))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Cerberus.ATC.GatewayV2Service.wsParametricas.CSParObtenerVehiculoTipos))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Cerberus.ATC.GatewayV2Service.wsParametricas.CSParObtenerVehiculoUsos))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Cerberus.ATC.GatewayV2Service.wsParametricas.CSParObtenerDepartamentos))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Cerberus.ATC.GatewayV2Service.wsParametricas.CSParObtenerFacturaTipo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Cerberus.ATC.GatewayV2Service.wsParametricas.CSParObtenerGestion))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Cerberus.ATC.GatewayV2Service.wsParametricas.CSParObtenerMedioPago))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Cerberus.ATC.GatewayV2Service.wsParametricas.CSParObtenerVentaCanal))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Cerberus.ATC.GatewayV2Service.wsParametricas.CSParObtenerBancos))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Cerberus.ATC.GatewayV2Service.wsParametricas.CSParObtenerPlacasTipo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Cerberus.ATC.GatewayV2Service.wsParametricas.CSParObtenerPrimas))]
    public partial class CSModulos : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoRetornoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ExitoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoRetorno {
            get {
                return this.CodigoRetornoField;
            }
            set {
                if ((this.CodigoRetornoField.Equals(value) != true)) {
                    this.CodigoRetornoField = value;
                    this.RaisePropertyChanged("CodigoRetorno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Exito {
            get {
                return this.ExitoField;
            }
            set {
                if ((this.ExitoField.Equals(value) != true)) {
                    this.ExitoField = value;
                    this.RaisePropertyChanged("Exito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CSPar", Namespace="http://schemas.datacontract.org/2004/07/ExternosNegociosCoreSoat.Modulos.Parametr" +
        "icas.ClasesSalida")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Cerberus.ATC.GatewayV2Service.wsParametricas.CSParObtenerVehiculoTipos))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Cerberus.ATC.GatewayV2Service.wsParametricas.CSParObtenerVehiculoUsos))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Cerberus.ATC.GatewayV2Service.wsParametricas.CSParObtenerDepartamentos))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Cerberus.ATC.GatewayV2Service.wsParametricas.CSParObtenerFacturaTipo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Cerberus.ATC.GatewayV2Service.wsParametricas.CSParObtenerGestion))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Cerberus.ATC.GatewayV2Service.wsParametricas.CSParObtenerMedioPago))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Cerberus.ATC.GatewayV2Service.wsParametricas.CSParObtenerVentaCanal))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Cerberus.ATC.GatewayV2Service.wsParametricas.CSParObtenerBancos))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Cerberus.ATC.GatewayV2Service.wsParametricas.CSParObtenerPlacasTipo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Cerberus.ATC.GatewayV2Service.wsParametricas.CSParObtenerPrimas))]
    public partial class CSPar : Cerberus.ATC.GatewayV2Service.wsParametricas.CSModulos {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CSParObtenerVehiculoTipos", Namespace="http://schemas.datacontract.org/2004/07/ExternosNegociosCoreSoat.Modulos.Parametr" +
        "icas.ClasesSalida")]
    [System.SerializableAttribute()]
    public partial class CSParObtenerVehiculoTipos : Cerberus.ATC.GatewayV2Service.wsParametricas.CSPar {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Cerberus.ATC.GatewayV2Service.wsParametricas.CVehiculoTipo[] lVehiculoTipoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Cerberus.ATC.GatewayV2Service.wsParametricas.CVehiculoTipo[] lVehiculoTipo {
            get {
                return this.lVehiculoTipoField;
            }
            set {
                if ((object.ReferenceEquals(this.lVehiculoTipoField, value) != true)) {
                    this.lVehiculoTipoField = value;
                    this.RaisePropertyChanged("lVehiculoTipo");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CSParObtenerVehiculoUsos", Namespace="http://schemas.datacontract.org/2004/07/ExternosNegociosCoreSoat.Modulos.Parametr" +
        "icas.ClasesSalida")]
    [System.SerializableAttribute()]
    public partial class CSParObtenerVehiculoUsos : Cerberus.ATC.GatewayV2Service.wsParametricas.CSPar {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Cerberus.ATC.GatewayV2Service.wsParametricas.CVehiculoUso[] lVehiculoUsoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Cerberus.ATC.GatewayV2Service.wsParametricas.CVehiculoUso[] lVehiculoUso {
            get {
                return this.lVehiculoUsoField;
            }
            set {
                if ((object.ReferenceEquals(this.lVehiculoUsoField, value) != true)) {
                    this.lVehiculoUsoField = value;
                    this.RaisePropertyChanged("lVehiculoUso");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CSParObtenerDepartamentos", Namespace="http://schemas.datacontract.org/2004/07/ExternosNegociosCoreSoat.Modulos.Parametr" +
        "icas.ClasesSalida")]
    [System.SerializableAttribute()]
    public partial class CSParObtenerDepartamentos : Cerberus.ATC.GatewayV2Service.wsParametricas.CSPar {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Cerberus.ATC.GatewayV2Service.wsParametricas.CDepartamento[] lDepartamentoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Cerberus.ATC.GatewayV2Service.wsParametricas.CDepartamento[] lDepartamento {
            get {
                return this.lDepartamentoField;
            }
            set {
                if ((object.ReferenceEquals(this.lDepartamentoField, value) != true)) {
                    this.lDepartamentoField = value;
                    this.RaisePropertyChanged("lDepartamento");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CSParObtenerFacturaTipo", Namespace="http://schemas.datacontract.org/2004/07/ExternosNegociosCoreSoat.Modulos.Parametr" +
        "icas.ClasesSalida")]
    [System.SerializableAttribute()]
    public partial class CSParObtenerFacturaTipo : Cerberus.ATC.GatewayV2Service.wsParametricas.CSPar {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Cerberus.ATC.GatewayV2Service.wsParametricas.CFacturaTipoL[] lFacturaTipoLField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Cerberus.ATC.GatewayV2Service.wsParametricas.CFacturaTipoL[] lFacturaTipoL {
            get {
                return this.lFacturaTipoLField;
            }
            set {
                if ((object.ReferenceEquals(this.lFacturaTipoLField, value) != true)) {
                    this.lFacturaTipoLField = value;
                    this.RaisePropertyChanged("lFacturaTipoL");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CSParObtenerGestion", Namespace="http://schemas.datacontract.org/2004/07/ExternosNegociosCoreSoat.Modulos.Parametr" +
        "icas.ClasesSalida")]
    [System.SerializableAttribute()]
    public partial class CSParObtenerGestion : Cerberus.ATC.GatewayV2Service.wsParametricas.CSPar {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Cerberus.ATC.GatewayV2Service.wsParametricas.CGestionLHabilitadas[] lGestionLHabilitadasField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Cerberus.ATC.GatewayV2Service.wsParametricas.CGestionLHabilitadas[] lGestionLHabilitadas {
            get {
                return this.lGestionLHabilitadasField;
            }
            set {
                if ((object.ReferenceEquals(this.lGestionLHabilitadasField, value) != true)) {
                    this.lGestionLHabilitadasField = value;
                    this.RaisePropertyChanged("lGestionLHabilitadas");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CSParObtenerMedioPago", Namespace="http://schemas.datacontract.org/2004/07/ExternosNegociosCoreSoat.Modulos.Parametr" +
        "icas.ClasesSalida")]
    [System.SerializableAttribute()]
    public partial class CSParObtenerMedioPago : Cerberus.ATC.GatewayV2Service.wsParametricas.CSPar {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Cerberus.ATC.GatewayV2Service.wsParametricas.CMedioPagoL[] lMedioPagoLField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Cerberus.ATC.GatewayV2Service.wsParametricas.CMedioPagoL[] lMedioPagoL {
            get {
                return this.lMedioPagoLField;
            }
            set {
                if ((object.ReferenceEquals(this.lMedioPagoLField, value) != true)) {
                    this.lMedioPagoLField = value;
                    this.RaisePropertyChanged("lMedioPagoL");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CSParObtenerVentaCanal", Namespace="http://schemas.datacontract.org/2004/07/ExternosNegociosCoreSoat.Modulos.Parametr" +
        "icas.ClasesSalida")]
    [System.SerializableAttribute()]
    public partial class CSParObtenerVentaCanal : Cerberus.ATC.GatewayV2Service.wsParametricas.CSPar {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Cerberus.ATC.GatewayV2Service.wsParametricas.CVentaCanalL[] lVentaCanalLField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Cerberus.ATC.GatewayV2Service.wsParametricas.CVentaCanalL[] lVentaCanalL {
            get {
                return this.lVentaCanalLField;
            }
            set {
                if ((object.ReferenceEquals(this.lVentaCanalLField, value) != true)) {
                    this.lVentaCanalLField = value;
                    this.RaisePropertyChanged("lVentaCanalL");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CSParObtenerBancos", Namespace="http://schemas.datacontract.org/2004/07/ExternosNegociosCoreSoat.Modulos.Parametr" +
        "icas.ClasesSalida")]
    [System.SerializableAttribute()]
    public partial class CSParObtenerBancos : Cerberus.ATC.GatewayV2Service.wsParametricas.CSPar {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Cerberus.ATC.GatewayV2Service.wsParametricas.CBancos[] lBancosField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Cerberus.ATC.GatewayV2Service.wsParametricas.CBancos[] lBancos {
            get {
                return this.lBancosField;
            }
            set {
                if ((object.ReferenceEquals(this.lBancosField, value) != true)) {
                    this.lBancosField = value;
                    this.RaisePropertyChanged("lBancos");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CSParObtenerPlacasTipo", Namespace="http://schemas.datacontract.org/2004/07/ExternosNegociosCoreSoat.Modulos.Parametr" +
        "icas.ClasesSalida")]
    [System.SerializableAttribute()]
    public partial class CSParObtenerPlacasTipo : Cerberus.ATC.GatewayV2Service.wsParametricas.CSPar {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Cerberus.ATC.GatewayV2Service.wsParametricas.CPlacasTipo[] lPlacasTipoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Cerberus.ATC.GatewayV2Service.wsParametricas.CPlacasTipo[] lPlacasTipo {
            get {
                return this.lPlacasTipoField;
            }
            set {
                if ((object.ReferenceEquals(this.lPlacasTipoField, value) != true)) {
                    this.lPlacasTipoField = value;
                    this.RaisePropertyChanged("lPlacasTipo");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CSParObtenerPrimas", Namespace="http://schemas.datacontract.org/2004/07/ExternosNegociosCoreSoat.Modulos.Parametr" +
        "icas.ClasesSalida")]
    [System.SerializableAttribute()]
    public partial class CSParObtenerPrimas : Cerberus.ATC.GatewayV2Service.wsParametricas.CSPar {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Cerberus.ATC.GatewayV2Service.wsParametricas.CPrima[] lPrimaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Cerberus.ATC.GatewayV2Service.wsParametricas.CPrima[] lPrima {
            get {
                return this.lPrimaField;
            }
            set {
                if ((object.ReferenceEquals(this.lPrimaField, value) != true)) {
                    this.lPrimaField = value;
                    this.RaisePropertyChanged("lPrima");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CPrima", Namespace="http://schemas.datacontract.org/2004/07/ExternosAgenteServiciosCoreSoat.Modulos.P" +
        "arametricas.EntidadesSalida")]
    [System.SerializableAttribute()]
    public partial class CPrima : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartamentoVentaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartamentoVentaDescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GestionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PrimaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int VehiculoTipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VehiculoTipoDescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int VehiculoUsoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VehiculoUsoDescripcionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DepartamentoVenta {
            get {
                return this.DepartamentoVentaField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartamentoVentaField, value) != true)) {
                    this.DepartamentoVentaField = value;
                    this.RaisePropertyChanged("DepartamentoVenta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DepartamentoVentaDescripcion {
            get {
                return this.DepartamentoVentaDescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartamentoVentaDescripcionField, value) != true)) {
                    this.DepartamentoVentaDescripcionField = value;
                    this.RaisePropertyChanged("DepartamentoVentaDescripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Gestion {
            get {
                return this.GestionField;
            }
            set {
                if ((this.GestionField.Equals(value) != true)) {
                    this.GestionField = value;
                    this.RaisePropertyChanged("Gestion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Prima {
            get {
                return this.PrimaField;
            }
            set {
                if ((this.PrimaField.Equals(value) != true)) {
                    this.PrimaField = value;
                    this.RaisePropertyChanged("Prima");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int VehiculoTipo {
            get {
                return this.VehiculoTipoField;
            }
            set {
                if ((this.VehiculoTipoField.Equals(value) != true)) {
                    this.VehiculoTipoField = value;
                    this.RaisePropertyChanged("VehiculoTipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VehiculoTipoDescripcion {
            get {
                return this.VehiculoTipoDescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.VehiculoTipoDescripcionField, value) != true)) {
                    this.VehiculoTipoDescripcionField = value;
                    this.RaisePropertyChanged("VehiculoTipoDescripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int VehiculoUso {
            get {
                return this.VehiculoUsoField;
            }
            set {
                if ((this.VehiculoUsoField.Equals(value) != true)) {
                    this.VehiculoUsoField = value;
                    this.RaisePropertyChanged("VehiculoUso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VehiculoUsoDescripcion {
            get {
                return this.VehiculoUsoDescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.VehiculoUsoDescripcionField, value) != true)) {
                    this.VehiculoUsoDescripcionField = value;
                    this.RaisePropertyChanged("VehiculoUsoDescripcion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CVehiculoTipo", Namespace="http://schemas.datacontract.org/2004/07/ExternosAgenteServiciosCoreSoat.Modulos.P" +
        "arametricas.EntidadesSaida")]
    [System.SerializableAttribute()]
    public partial class CVehiculoTipo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SecuencialField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Secuencial {
            get {
                return this.SecuencialField;
            }
            set {
                if ((this.SecuencialField.Equals(value) != true)) {
                    this.SecuencialField = value;
                    this.RaisePropertyChanged("Secuencial");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CVehiculoUso", Namespace="http://schemas.datacontract.org/2004/07/ExternosAgenteServiciosCoreSoat.Modulos.P" +
        "arametricas.EntidadesSaida")]
    [System.SerializableAttribute()]
    public partial class CVehiculoUso : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SecuencialField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Secuencial {
            get {
                return this.SecuencialField;
            }
            set {
                if ((this.SecuencialField.Equals(value) != true)) {
                    this.SecuencialField = value;
                    this.RaisePropertyChanged("Secuencial");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CDepartamento", Namespace="http://schemas.datacontract.org/2004/07/ExternosAgenteServiciosCoreSoat.Modulos.P" +
        "arametricas.EntidadesSaida")]
    [System.SerializableAttribute()]
    public partial class CDepartamento : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoDepartamentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoDepartamento {
            get {
                return this.CodigoDepartamentoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoDepartamentoField, value) != true)) {
                    this.CodigoDepartamentoField = value;
                    this.RaisePropertyChanged("CodigoDepartamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CFacturaTipoL", Namespace="http://schemas.datacontract.org/2004/07/ExternosAgenteServiciosCoreSoat.Modulos.P" +
        "arametricas.EntidadesSaida")]
    [System.SerializableAttribute()]
    public partial class CFacturaTipoL : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SecuencialField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Secuencial {
            get {
                return this.SecuencialField;
            }
            set {
                if ((this.SecuencialField.Equals(value) != true)) {
                    this.SecuencialField = value;
                    this.RaisePropertyChanged("Secuencial");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CGestionLHabilitadas", Namespace="http://schemas.datacontract.org/2004/07/ExternosAgenteServiciosCoreSoat.Modulos.P" +
        "arametricas.EntidadesSaida")]
    [System.SerializableAttribute()]
    public partial class CGestionLHabilitadas : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PrioridadVentaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SecuencialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime VentaDesdeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime VentaHastaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PrioridadVenta {
            get {
                return this.PrioridadVentaField;
            }
            set {
                if ((this.PrioridadVentaField.Equals(value) != true)) {
                    this.PrioridadVentaField = value;
                    this.RaisePropertyChanged("PrioridadVenta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Secuencial {
            get {
                return this.SecuencialField;
            }
            set {
                if ((this.SecuencialField.Equals(value) != true)) {
                    this.SecuencialField = value;
                    this.RaisePropertyChanged("Secuencial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime VentaDesde {
            get {
                return this.VentaDesdeField;
            }
            set {
                if ((this.VentaDesdeField.Equals(value) != true)) {
                    this.VentaDesdeField = value;
                    this.RaisePropertyChanged("VentaDesde");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime VentaHasta {
            get {
                return this.VentaHastaField;
            }
            set {
                if ((this.VentaHastaField.Equals(value) != true)) {
                    this.VentaHastaField = value;
                    this.RaisePropertyChanged("VentaHasta");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CMedioPagoL", Namespace="http://schemas.datacontract.org/2004/07/ExternosAgenteServiciosCoreSoat.Modulos.P" +
        "arametricas.EntidadesSaida")]
    [System.SerializableAttribute()]
    public partial class CMedioPagoL : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DatosCompletosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SecuencialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecuencialMasDatoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DatosCompletos {
            get {
                return this.DatosCompletosField;
            }
            set {
                if ((object.ReferenceEquals(this.DatosCompletosField, value) != true)) {
                    this.DatosCompletosField = value;
                    this.RaisePropertyChanged("DatosCompletos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Secuencial {
            get {
                return this.SecuencialField;
            }
            set {
                if ((this.SecuencialField.Equals(value) != true)) {
                    this.SecuencialField = value;
                    this.RaisePropertyChanged("Secuencial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SecuencialMasDato {
            get {
                return this.SecuencialMasDatoField;
            }
            set {
                if ((object.ReferenceEquals(this.SecuencialMasDatoField, value) != true)) {
                    this.SecuencialMasDatoField = value;
                    this.RaisePropertyChanged("SecuencialMasDato");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CVentaCanalL", Namespace="http://schemas.datacontract.org/2004/07/ExternosAgenteServiciosCoreSoat.Modulos.P" +
        "arametricas.EntidadesSaida")]
    [System.SerializableAttribute()]
    public partial class CVentaCanalL : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HabilitadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SecuencialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TIntermediarioFkField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Habilitado {
            get {
                return this.HabilitadoField;
            }
            set {
                if ((this.HabilitadoField.Equals(value) != true)) {
                    this.HabilitadoField = value;
                    this.RaisePropertyChanged("Habilitado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Secuencial {
            get {
                return this.SecuencialField;
            }
            set {
                if ((this.SecuencialField.Equals(value) != true)) {
                    this.SecuencialField = value;
                    this.RaisePropertyChanged("Secuencial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TIntermediarioFk {
            get {
                return this.TIntermediarioFkField;
            }
            set {
                if ((this.TIntermediarioFkField.Equals(value) != true)) {
                    this.TIntermediarioFkField = value;
                    this.RaisePropertyChanged("TIntermediarioFk");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CBancos", Namespace="http://schemas.datacontract.org/2004/07/ExternosAgenteServiciosCoreSoat.Modulos.P" +
        "arametricas.EntidadesSaida")]
    [System.SerializableAttribute()]
    public partial class CBancos : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SecuencialField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Secuencial {
            get {
                return this.SecuencialField;
            }
            set {
                if ((this.SecuencialField.Equals(value) != true)) {
                    this.SecuencialField = value;
                    this.RaisePropertyChanged("Secuencial");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CPlacasTipo", Namespace="http://schemas.datacontract.org/2004/07/ExternosAgenteServiciosCoreSoat.Modulos.P" +
        "arametricas.EntidadesSaida")]
    [System.SerializableAttribute()]
    public partial class CPlacasTipo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HabilitadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SecuencialField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Habilitado {
            get {
                return this.HabilitadoField;
            }
            set {
                if ((this.HabilitadoField.Equals(value) != true)) {
                    this.HabilitadoField = value;
                    this.RaisePropertyChanged("Habilitado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Secuencial {
            get {
                return this.SecuencialField;
            }
            set {
                if ((this.SecuencialField.Equals(value) != true)) {
                    this.SecuencialField = value;
                    this.RaisePropertyChanged("Secuencial");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsParametricas.IwsParametricas")]
    public interface IwsParametricas {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsParametricas/ParObtenerPrimas", ReplyAction="http://tempuri.org/IwsParametricas/ParObtenerPrimasResponse")]
        Cerberus.ATC.GatewayV2Service.wsParametricas.CSParObtenerPrimas ParObtenerPrimas(Cerberus.ATC.GatewayV2Service.wsParametricas.CEParObtenerPrimas oEParObtenerPrimas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsParametricas/ParObtenerVehiculoTipos", ReplyAction="http://tempuri.org/IwsParametricas/ParObtenerVehiculoTiposResponse")]
        Cerberus.ATC.GatewayV2Service.wsParametricas.CSParObtenerVehiculoTipos ParObtenerVehiculoTipos(Cerberus.ATC.GatewayV2Service.wsParametricas.CEParObtenerVehiculoTipos oEParObtenerVehiculoTipos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsParametricas/ParObtenerVehiculoUsos", ReplyAction="http://tempuri.org/IwsParametricas/ParObtenerVehiculoUsosResponse")]
        Cerberus.ATC.GatewayV2Service.wsParametricas.CSParObtenerVehiculoUsos ParObtenerVehiculoUsos(Cerberus.ATC.GatewayV2Service.wsParametricas.CEParObtenerVehiculoUsos oEParObtenerVehiculoUsos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsParametricas/ParObtenerDepartamentos", ReplyAction="http://tempuri.org/IwsParametricas/ParObtenerDepartamentosResponse")]
        Cerberus.ATC.GatewayV2Service.wsParametricas.CSParObtenerDepartamentos ParObtenerDepartamentos(Cerberus.ATC.GatewayV2Service.wsParametricas.CEParObtenerDepartamentos oEParObtenerDepartamentos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsParametricas/ParObtenerFacturaTipo", ReplyAction="http://tempuri.org/IwsParametricas/ParObtenerFacturaTipoResponse")]
        Cerberus.ATC.GatewayV2Service.wsParametricas.CSParObtenerFacturaTipo ParObtenerFacturaTipo(Cerberus.ATC.GatewayV2Service.wsParametricas.CEParObtenerFacturaTipo oEParObtenerFacturaTipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsParametricas/ParObtenerGestion", ReplyAction="http://tempuri.org/IwsParametricas/ParObtenerGestionResponse")]
        Cerberus.ATC.GatewayV2Service.wsParametricas.CSParObtenerGestion ParObtenerGestion(Cerberus.ATC.GatewayV2Service.wsParametricas.CEParObtenerGestion oEParObtenerGestion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsParametricas/ParObtenerMedioPago", ReplyAction="http://tempuri.org/IwsParametricas/ParObtenerMedioPagoResponse")]
        Cerberus.ATC.GatewayV2Service.wsParametricas.CSParObtenerMedioPago ParObtenerMedioPago(Cerberus.ATC.GatewayV2Service.wsParametricas.CEParObtenerMedioPago oEParObtenerMedioPago);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsParametricas/ParObtenerVentaCanal", ReplyAction="http://tempuri.org/IwsParametricas/ParObtenerVentaCanalResponse")]
        Cerberus.ATC.GatewayV2Service.wsParametricas.CSParObtenerVentaCanal ParObtenerVentaCanal(Cerberus.ATC.GatewayV2Service.wsParametricas.CEParObtenerVentaCanal oEParObtenerVentaCanal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsParametricas/ParObtenerBancos", ReplyAction="http://tempuri.org/IwsParametricas/ParObtenerBancosResponse")]
        Cerberus.ATC.GatewayV2Service.wsParametricas.CSParObtenerBancos ParObtenerBancos(Cerberus.ATC.GatewayV2Service.wsParametricas.CEParObtenerBancos oEParObtenerBancos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsParametricas/ParObtenerPlacasTipo", ReplyAction="http://tempuri.org/IwsParametricas/ParObtenerPlacasTipoResponse")]
        Cerberus.ATC.GatewayV2Service.wsParametricas.CSParObtenerPlacasTipo ParObtenerPlacasTipo(Cerberus.ATC.GatewayV2Service.wsParametricas.CEParObtenerPlacasTipo oEParObtenerPlacasTipo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IwsParametricasChannel : Cerberus.ATC.GatewayV2Service.wsParametricas.IwsParametricas, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IwsParametricasClient : System.ServiceModel.ClientBase<Cerberus.ATC.GatewayV2Service.wsParametricas.IwsParametricas>, Cerberus.ATC.GatewayV2Service.wsParametricas.IwsParametricas {
        
        public IwsParametricasClient() {
        }
        
        public IwsParametricasClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IwsParametricasClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IwsParametricasClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IwsParametricasClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Cerberus.ATC.GatewayV2Service.wsParametricas.CSParObtenerPrimas ParObtenerPrimas(Cerberus.ATC.GatewayV2Service.wsParametricas.CEParObtenerPrimas oEParObtenerPrimas) {
            return base.Channel.ParObtenerPrimas(oEParObtenerPrimas);
        }
        
        public Cerberus.ATC.GatewayV2Service.wsParametricas.CSParObtenerVehiculoTipos ParObtenerVehiculoTipos(Cerberus.ATC.GatewayV2Service.wsParametricas.CEParObtenerVehiculoTipos oEParObtenerVehiculoTipos) {
            return base.Channel.ParObtenerVehiculoTipos(oEParObtenerVehiculoTipos);
        }
        
        public Cerberus.ATC.GatewayV2Service.wsParametricas.CSParObtenerVehiculoUsos ParObtenerVehiculoUsos(Cerberus.ATC.GatewayV2Service.wsParametricas.CEParObtenerVehiculoUsos oEParObtenerVehiculoUsos) {
            return base.Channel.ParObtenerVehiculoUsos(oEParObtenerVehiculoUsos);
        }
        
        public Cerberus.ATC.GatewayV2Service.wsParametricas.CSParObtenerDepartamentos ParObtenerDepartamentos(Cerberus.ATC.GatewayV2Service.wsParametricas.CEParObtenerDepartamentos oEParObtenerDepartamentos) {
            return base.Channel.ParObtenerDepartamentos(oEParObtenerDepartamentos);
        }
        
        public Cerberus.ATC.GatewayV2Service.wsParametricas.CSParObtenerFacturaTipo ParObtenerFacturaTipo(Cerberus.ATC.GatewayV2Service.wsParametricas.CEParObtenerFacturaTipo oEParObtenerFacturaTipo) {
            return base.Channel.ParObtenerFacturaTipo(oEParObtenerFacturaTipo);
        }
        
        public Cerberus.ATC.GatewayV2Service.wsParametricas.CSParObtenerGestion ParObtenerGestion(Cerberus.ATC.GatewayV2Service.wsParametricas.CEParObtenerGestion oEParObtenerGestion) {
            return base.Channel.ParObtenerGestion(oEParObtenerGestion);
        }
        
        public Cerberus.ATC.GatewayV2Service.wsParametricas.CSParObtenerMedioPago ParObtenerMedioPago(Cerberus.ATC.GatewayV2Service.wsParametricas.CEParObtenerMedioPago oEParObtenerMedioPago) {
            return base.Channel.ParObtenerMedioPago(oEParObtenerMedioPago);
        }
        
        public Cerberus.ATC.GatewayV2Service.wsParametricas.CSParObtenerVentaCanal ParObtenerVentaCanal(Cerberus.ATC.GatewayV2Service.wsParametricas.CEParObtenerVentaCanal oEParObtenerVentaCanal) {
            return base.Channel.ParObtenerVentaCanal(oEParObtenerVentaCanal);
        }
        
        public Cerberus.ATC.GatewayV2Service.wsParametricas.CSParObtenerBancos ParObtenerBancos(Cerberus.ATC.GatewayV2Service.wsParametricas.CEParObtenerBancos oEParObtenerBancos) {
            return base.Channel.ParObtenerBancos(oEParObtenerBancos);
        }
        
        public Cerberus.ATC.GatewayV2Service.wsParametricas.CSParObtenerPlacasTipo ParObtenerPlacasTipo(Cerberus.ATC.GatewayV2Service.wsParametricas.CEParObtenerPlacasTipo oEParObtenerPlacasTipo) {
            return base.Channel.ParObtenerPlacasTipo(oEParObtenerPlacasTipo);
        }
    }
}
