//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18034
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestFlujoWebServiceSOAT.wsReporteCierreVentas {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CEModulos", Namespace="http://schemas.datacontract.org/2004/07/ExternosNegociosCoreSoat.Modulos.ClasesBa" +
        "se")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestFlujoWebServiceSOAT.wsReporteCierreVentas.CERcv))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestFlujoWebServiceSOAT.wsReporteCierreVentas.CERcv11ListarVentas))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestFlujoWebServiceSOAT.wsReporteCierreVentas.CERcv12Efectivizar))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestFlujoWebServiceSOAT.wsReporteCierreVentas.CERcv13Remitir))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestFlujoWebServiceSOAT.wsReporteCierreVentas.CERcv14Listar))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestFlujoWebServiceSOAT.wsReporteCierreVentas.CERcv15Obtener))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestFlujoWebServiceSOAT.wsReporteCierreVentas.CERcv16Revertir))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestFlujoWebServiceSOAT.wsReporteCierreVentas.CERcv10ActualizarFechaLiquidacion))]
    public partial class CEModulos : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SoatTIntermediarioFkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SoatTIntermediarioFk {
            get {
                return this.SoatTIntermediarioFkField;
            }
            set {
                if ((this.SoatTIntermediarioFkField.Equals(value) != true)) {
                    this.SoatTIntermediarioFkField = value;
                    this.RaisePropertyChanged("SoatTIntermediarioFk");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usuario {
            get {
                return this.UsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioField, value) != true)) {
                    this.UsuarioField = value;
                    this.RaisePropertyChanged("Usuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CERcv", Namespace="http://schemas.datacontract.org/2004/07/ExternosNegociosCoreSoat.Modulos.ReporteC" +
        "ierreVentas.ClasesEntrada")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestFlujoWebServiceSOAT.wsReporteCierreVentas.CERcv11ListarVentas))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestFlujoWebServiceSOAT.wsReporteCierreVentas.CERcv12Efectivizar))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestFlujoWebServiceSOAT.wsReporteCierreVentas.CERcv13Remitir))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestFlujoWebServiceSOAT.wsReporteCierreVentas.CERcv14Listar))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestFlujoWebServiceSOAT.wsReporteCierreVentas.CERcv15Obtener))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestFlujoWebServiceSOAT.wsReporteCierreVentas.CERcv16Revertir))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestFlujoWebServiceSOAT.wsReporteCierreVentas.CERcv10ActualizarFechaLiquidacion))]
    public partial class CERcv : TestFlujoWebServiceSOAT.wsReporteCierreVentas.CEModulos {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SeguridadTokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SoatTParGestionFkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SoatTParVentaCanalFkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SoatVentaVendedorField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SeguridadToken {
            get {
                return this.SeguridadTokenField;
            }
            set {
                if ((this.SeguridadTokenField.Equals(value) != true)) {
                    this.SeguridadTokenField = value;
                    this.RaisePropertyChanged("SeguridadToken");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SoatTParGestionFk {
            get {
                return this.SoatTParGestionFkField;
            }
            set {
                if ((this.SoatTParGestionFkField.Equals(value) != true)) {
                    this.SoatTParGestionFkField = value;
                    this.RaisePropertyChanged("SoatTParGestionFk");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SoatTParVentaCanalFk {
            get {
                return this.SoatTParVentaCanalFkField;
            }
            set {
                if ((this.SoatTParVentaCanalFkField.Equals(value) != true)) {
                    this.SoatTParVentaCanalFkField = value;
                    this.RaisePropertyChanged("SoatTParVentaCanalFk");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SoatVentaVendedor {
            get {
                return this.SoatVentaVendedorField;
            }
            set {
                if ((object.ReferenceEquals(this.SoatVentaVendedorField, value) != true)) {
                    this.SoatVentaVendedorField = value;
                    this.RaisePropertyChanged("SoatVentaVendedor");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CERcv11ListarVentas", Namespace="http://schemas.datacontract.org/2004/07/ExternosNegociosCoreSoat.Modulos.ReporteC" +
        "ierreVentas.ClasesEntrada")]
    [System.SerializableAttribute()]
    public partial class CERcv11ListarVentas : TestFlujoWebServiceSOAT.wsReporteCierreVentas.CERcv {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime SoatVentaFechaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SoatVentaFecha {
            get {
                return this.SoatVentaFechaField;
            }
            set {
                if ((this.SoatVentaFechaField.Equals(value) != true)) {
                    this.SoatVentaFechaField = value;
                    this.RaisePropertyChanged("SoatVentaFecha");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CERcv12Efectivizar", Namespace="http://schemas.datacontract.org/2004/07/ExternosNegociosCoreSoat.Modulos.ReporteC" +
        "ierreVentas.ClasesEntrada")]
    [System.SerializableAttribute()]
    public partial class CERcv12Efectivizar : TestFlujoWebServiceSOAT.wsReporteCierreVentas.CERcv {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RcvCantidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal RcvImporteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RcvJsonMedioPagoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RcvTSucursalFkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime SoatVentaFechaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RcvCantidad {
            get {
                return this.RcvCantidadField;
            }
            set {
                if ((this.RcvCantidadField.Equals(value) != true)) {
                    this.RcvCantidadField = value;
                    this.RaisePropertyChanged("RcvCantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal RcvImporte {
            get {
                return this.RcvImporteField;
            }
            set {
                if ((this.RcvImporteField.Equals(value) != true)) {
                    this.RcvImporteField = value;
                    this.RaisePropertyChanged("RcvImporte");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RcvJsonMedioPago {
            get {
                return this.RcvJsonMedioPagoField;
            }
            set {
                if ((object.ReferenceEquals(this.RcvJsonMedioPagoField, value) != true)) {
                    this.RcvJsonMedioPagoField = value;
                    this.RaisePropertyChanged("RcvJsonMedioPago");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RcvTSucursalFk {
            get {
                return this.RcvTSucursalFkField;
            }
            set {
                if ((this.RcvTSucursalFkField.Equals(value) != true)) {
                    this.RcvTSucursalFkField = value;
                    this.RaisePropertyChanged("RcvTSucursalFk");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SoatVentaFecha {
            get {
                return this.SoatVentaFechaField;
            }
            set {
                if ((this.SoatVentaFechaField.Equals(value) != true)) {
                    this.SoatVentaFechaField = value;
                    this.RaisePropertyChanged("SoatVentaFecha");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CERcv13Remitir", Namespace="http://schemas.datacontract.org/2004/07/ExternosNegociosCoreSoat.Modulos.ReporteC" +
        "ierreVentas.ClasesEntrada")]
    [System.SerializableAttribute()]
    public partial class CERcv13Remitir : TestFlujoWebServiceSOAT.wsReporteCierreVentas.CERcv {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RcvSecuencialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestFlujoWebServiceSOAT.wsReporteCierreVentas.CArchivosAdjuntos oArchivosAdjuntosField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RcvSecuencial {
            get {
                return this.RcvSecuencialField;
            }
            set {
                if ((this.RcvSecuencialField.Equals(value) != true)) {
                    this.RcvSecuencialField = value;
                    this.RaisePropertyChanged("RcvSecuencial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestFlujoWebServiceSOAT.wsReporteCierreVentas.CArchivosAdjuntos oArchivosAdjuntos {
            get {
                return this.oArchivosAdjuntosField;
            }
            set {
                if ((object.ReferenceEquals(this.oArchivosAdjuntosField, value) != true)) {
                    this.oArchivosAdjuntosField = value;
                    this.RaisePropertyChanged("oArchivosAdjuntos");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CERcv14Listar", Namespace="http://schemas.datacontract.org/2004/07/ExternosNegociosCoreSoat.Modulos.ReporteC" +
        "ierreVentas.ClasesEntrada")]
    [System.SerializableAttribute()]
    public partial class CERcv14Listar : TestFlujoWebServiceSOAT.wsReporteCierreVentas.CERcv {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CERcv15Obtener", Namespace="http://schemas.datacontract.org/2004/07/ExternosNegociosCoreSoat.Modulos.ReporteC" +
        "ierreVentas.ClasesEntrada")]
    [System.SerializableAttribute()]
    public partial class CERcv15Obtener : TestFlujoWebServiceSOAT.wsReporteCierreVentas.CERcv {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RcvSecuencialField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RcvSecuencial {
            get {
                return this.RcvSecuencialField;
            }
            set {
                if ((this.RcvSecuencialField.Equals(value) != true)) {
                    this.RcvSecuencialField = value;
                    this.RaisePropertyChanged("RcvSecuencial");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CERcv16Revertir", Namespace="http://schemas.datacontract.org/2004/07/ExternosNegociosCoreSoat.Modulos.ReporteC" +
        "ierreVentas.ClasesEntrada")]
    [System.SerializableAttribute()]
    public partial class CERcv16Revertir : TestFlujoWebServiceSOAT.wsReporteCierreVentas.CERcv {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RcvSecuencialField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RcvSecuencial {
            get {
                return this.RcvSecuencialField;
            }
            set {
                if ((this.RcvSecuencialField.Equals(value) != true)) {
                    this.RcvSecuencialField = value;
                    this.RaisePropertyChanged("RcvSecuencial");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CERcv10ActualizarFechaLiquidacion", Namespace="http://schemas.datacontract.org/2004/07/ExternosNegociosCoreSoat.Modulos.ReporteC" +
        "ierreVentas.ClasesEntrada")]
    [System.SerializableAttribute()]
    public partial class CERcv10ActualizarFechaLiquidacion : TestFlujoWebServiceSOAT.wsReporteCierreVentas.CERcv {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestFlujoWebServiceSOAT.wsReporteCierreVentas.CDatosLiquidacionMaestro[] lDatosLiquidacionMaestroField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestFlujoWebServiceSOAT.wsReporteCierreVentas.CDatosLiquidacionMaestro[] lDatosLiquidacionMaestro {
            get {
                return this.lDatosLiquidacionMaestroField;
            }
            set {
                if ((object.ReferenceEquals(this.lDatosLiquidacionMaestroField, value) != true)) {
                    this.lDatosLiquidacionMaestroField = value;
                    this.RaisePropertyChanged("lDatosLiquidacionMaestro");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CDatosLiquidacionMaestro", Namespace="http://schemas.datacontract.org/2004/07/BibliotecaCoreSoat.Modulos.ReporteCierreV" +
        "entas.Entidades")]
    [System.SerializableAttribute()]
    public partial class CDatosLiquidacionMaestro : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaLiquidacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SoatNroComprobanteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestFlujoWebServiceSOAT.wsReporteCierreVentas.CDatosLiquidacionDetalle oDatosLiquidacionDetalleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaLiquidacion {
            get {
                return this.FechaLiquidacionField;
            }
            set {
                if ((this.FechaLiquidacionField.Equals(value) != true)) {
                    this.FechaLiquidacionField = value;
                    this.RaisePropertyChanged("FechaLiquidacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SoatNroComprobante {
            get {
                return this.SoatNroComprobanteField;
            }
            set {
                if ((this.SoatNroComprobanteField.Equals(value) != true)) {
                    this.SoatNroComprobanteField = value;
                    this.RaisePropertyChanged("SoatNroComprobante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestFlujoWebServiceSOAT.wsReporteCierreVentas.CDatosLiquidacionDetalle oDatosLiquidacionDetalle {
            get {
                return this.oDatosLiquidacionDetalleField;
            }
            set {
                if ((object.ReferenceEquals(this.oDatosLiquidacionDetalleField, value) != true)) {
                    this.oDatosLiquidacionDetalleField = value;
                    this.RaisePropertyChanged("oDatosLiquidacionDetalle");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CArchivosAdjuntos", Namespace="http://schemas.datacontract.org/2004/07/UVNetTransversal.AgenteServicios.Almacena" +
        "miento.Archivos.EntidadesSalida")]
    [System.SerializableAttribute()]
    public partial class CArchivosAdjuntos : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ArchivoAdjuntoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ArchivoDescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ArchivoDirectorioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ArchivoExtensionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ArchivoLongitudField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ArchivoNombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ArchivoTipoContenidoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] ArchivoAdjunto {
            get {
                return this.ArchivoAdjuntoField;
            }
            set {
                if ((object.ReferenceEquals(this.ArchivoAdjuntoField, value) != true)) {
                    this.ArchivoAdjuntoField = value;
                    this.RaisePropertyChanged("ArchivoAdjunto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ArchivoDescripcion {
            get {
                return this.ArchivoDescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.ArchivoDescripcionField, value) != true)) {
                    this.ArchivoDescripcionField = value;
                    this.RaisePropertyChanged("ArchivoDescripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ArchivoDirectorio {
            get {
                return this.ArchivoDirectorioField;
            }
            set {
                if ((object.ReferenceEquals(this.ArchivoDirectorioField, value) != true)) {
                    this.ArchivoDirectorioField = value;
                    this.RaisePropertyChanged("ArchivoDirectorio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ArchivoExtension {
            get {
                return this.ArchivoExtensionField;
            }
            set {
                if ((object.ReferenceEquals(this.ArchivoExtensionField, value) != true)) {
                    this.ArchivoExtensionField = value;
                    this.RaisePropertyChanged("ArchivoExtension");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ArchivoLongitud {
            get {
                return this.ArchivoLongitudField;
            }
            set {
                if ((this.ArchivoLongitudField.Equals(value) != true)) {
                    this.ArchivoLongitudField = value;
                    this.RaisePropertyChanged("ArchivoLongitud");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ArchivoNombre {
            get {
                return this.ArchivoNombreField;
            }
            set {
                if ((object.ReferenceEquals(this.ArchivoNombreField, value) != true)) {
                    this.ArchivoNombreField = value;
                    this.RaisePropertyChanged("ArchivoNombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ArchivoTipoContenido {
            get {
                return this.ArchivoTipoContenidoField;
            }
            set {
                if ((object.ReferenceEquals(this.ArchivoTipoContenidoField, value) != true)) {
                    this.ArchivoTipoContenidoField = value;
                    this.RaisePropertyChanged("ArchivoTipoContenido");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CDatosLiquidacionDetalle", Namespace="http://schemas.datacontract.org/2004/07/BibliotecaCoreSoat.Modulos.ReporteCierreV" +
        "entas.Entidades")]
    [System.SerializableAttribute()]
    public partial class CDatosLiquidacionDetalle : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoAutorizacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaOrigenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaProcesoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FillerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ImporteComisionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ImporteOrigenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MonedaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroComprobanteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroEstablecimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroTarjetaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SucursalZonaGeograficaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoAutorizacion {
            get {
                return this.CodigoAutorizacionField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoAutorizacionField, value) != true)) {
                    this.CodigoAutorizacionField = value;
                    this.RaisePropertyChanged("CodigoAutorizacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaOrigen {
            get {
                return this.FechaOrigenField;
            }
            set {
                if ((this.FechaOrigenField.Equals(value) != true)) {
                    this.FechaOrigenField = value;
                    this.RaisePropertyChanged("FechaOrigen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaProceso {
            get {
                return this.FechaProcesoField;
            }
            set {
                if ((this.FechaProcesoField.Equals(value) != true)) {
                    this.FechaProcesoField = value;
                    this.RaisePropertyChanged("FechaProceso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Filler {
            get {
                return this.FillerField;
            }
            set {
                if ((object.ReferenceEquals(this.FillerField, value) != true)) {
                    this.FillerField = value;
                    this.RaisePropertyChanged("Filler");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ImporteComision {
            get {
                return this.ImporteComisionField;
            }
            set {
                if ((this.ImporteComisionField.Equals(value) != true)) {
                    this.ImporteComisionField = value;
                    this.RaisePropertyChanged("ImporteComision");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ImporteOrigen {
            get {
                return this.ImporteOrigenField;
            }
            set {
                if ((this.ImporteOrigenField.Equals(value) != true)) {
                    this.ImporteOrigenField = value;
                    this.RaisePropertyChanged("ImporteOrigen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Moneda {
            get {
                return this.MonedaField;
            }
            set {
                if ((object.ReferenceEquals(this.MonedaField, value) != true)) {
                    this.MonedaField = value;
                    this.RaisePropertyChanged("Moneda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroComprobante {
            get {
                return this.NumeroComprobanteField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroComprobanteField, value) != true)) {
                    this.NumeroComprobanteField = value;
                    this.RaisePropertyChanged("NumeroComprobante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroEstablecimiento {
            get {
                return this.NumeroEstablecimientoField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroEstablecimientoField, value) != true)) {
                    this.NumeroEstablecimientoField = value;
                    this.RaisePropertyChanged("NumeroEstablecimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroTarjeta {
            get {
                return this.NumeroTarjetaField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroTarjetaField, value) != true)) {
                    this.NumeroTarjetaField = value;
                    this.RaisePropertyChanged("NumeroTarjeta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SucursalZonaGeografica {
            get {
                return this.SucursalZonaGeograficaField;
            }
            set {
                if ((object.ReferenceEquals(this.SucursalZonaGeograficaField, value) != true)) {
                    this.SucursalZonaGeograficaField = value;
                    this.RaisePropertyChanged("SucursalZonaGeografica");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CSModulos", Namespace="http://schemas.datacontract.org/2004/07/ExternosNegociosCoreSoat.Modulos.ClasesBa" +
        "se")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestFlujoWebServiceSOAT.wsReporteCierreVentas.CSRcv))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestFlujoWebServiceSOAT.wsReporteCierreVentas.CSRcv11ListarVentas))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestFlujoWebServiceSOAT.wsReporteCierreVentas.CSRcv12Efectivizar))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestFlujoWebServiceSOAT.wsReporteCierreVentas.CSRcv13Remitir))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestFlujoWebServiceSOAT.wsReporteCierreVentas.CSRcv14Listar))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestFlujoWebServiceSOAT.wsReporteCierreVentas.CSRcv15Obtener))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestFlujoWebServiceSOAT.wsReporteCierreVentas.CSRcv16Revertir))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestFlujoWebServiceSOAT.wsReporteCierreVentas.CSRcv10ActualizarFechaLiquidacion))]
    public partial class CSModulos : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoRetornoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ExitoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoRetorno {
            get {
                return this.CodigoRetornoField;
            }
            set {
                if ((this.CodigoRetornoField.Equals(value) != true)) {
                    this.CodigoRetornoField = value;
                    this.RaisePropertyChanged("CodigoRetorno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Exito {
            get {
                return this.ExitoField;
            }
            set {
                if ((this.ExitoField.Equals(value) != true)) {
                    this.ExitoField = value;
                    this.RaisePropertyChanged("Exito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CSRcv", Namespace="http://schemas.datacontract.org/2004/07/ExternosNegociosCoreSoat.Modulos.ReporteC" +
        "ierreVentas.ClasesSalida")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestFlujoWebServiceSOAT.wsReporteCierreVentas.CSRcv11ListarVentas))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestFlujoWebServiceSOAT.wsReporteCierreVentas.CSRcv12Efectivizar))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestFlujoWebServiceSOAT.wsReporteCierreVentas.CSRcv13Remitir))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestFlujoWebServiceSOAT.wsReporteCierreVentas.CSRcv14Listar))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestFlujoWebServiceSOAT.wsReporteCierreVentas.CSRcv15Obtener))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestFlujoWebServiceSOAT.wsReporteCierreVentas.CSRcv16Revertir))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestFlujoWebServiceSOAT.wsReporteCierreVentas.CSRcv10ActualizarFechaLiquidacion))]
    public partial class CSRcv : TestFlujoWebServiceSOAT.wsReporteCierreVentas.CSModulos {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CSRcv11ListarVentas", Namespace="http://schemas.datacontract.org/2004/07/ExternosNegociosCoreSoat.Modulos.ReporteC" +
        "ierreVentas.ClasesSalida")]
    [System.SerializableAttribute()]
    public partial class CSRcv11ListarVentas : TestFlujoWebServiceSOAT.wsReporteCierreVentas.CSRcv {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestFlujoWebServiceSOAT.wsReporteCierreVentas.CRcvDatosVentas oRcvDatosVentasField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestFlujoWebServiceSOAT.wsReporteCierreVentas.CRcvDatosVentas oRcvDatosVentas {
            get {
                return this.oRcvDatosVentasField;
            }
            set {
                if ((object.ReferenceEquals(this.oRcvDatosVentasField, value) != true)) {
                    this.oRcvDatosVentasField = value;
                    this.RaisePropertyChanged("oRcvDatosVentas");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CSRcv12Efectivizar", Namespace="http://schemas.datacontract.org/2004/07/ExternosNegociosCoreSoat.Modulos.ReporteC" +
        "ierreVentas.ClasesSalida")]
    [System.SerializableAttribute()]
    public partial class CSRcv12Efectivizar : TestFlujoWebServiceSOAT.wsReporteCierreVentas.CSRcv {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RcvSecuencialField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RcvSecuencial {
            get {
                return this.RcvSecuencialField;
            }
            set {
                if ((this.RcvSecuencialField.Equals(value) != true)) {
                    this.RcvSecuencialField = value;
                    this.RaisePropertyChanged("RcvSecuencial");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CSRcv13Remitir", Namespace="http://schemas.datacontract.org/2004/07/ExternosNegociosCoreSoat.Modulos.ReporteC" +
        "ierreVentas.ClasesSalida")]
    [System.SerializableAttribute()]
    public partial class CSRcv13Remitir : TestFlujoWebServiceSOAT.wsReporteCierreVentas.CSRcv {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CSRcv14Listar", Namespace="http://schemas.datacontract.org/2004/07/ExternosNegociosCoreSoat.Modulos.ReporteC" +
        "ierreVentas.ClasesSalida")]
    [System.SerializableAttribute()]
    public partial class CSRcv14Listar : TestFlujoWebServiceSOAT.wsReporteCierreVentas.CSRcv {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestFlujoWebServiceSOAT.wsReporteCierreVentas.CRcvDatos[] lRcvDatosField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestFlujoWebServiceSOAT.wsReporteCierreVentas.CRcvDatos[] lRcvDatos {
            get {
                return this.lRcvDatosField;
            }
            set {
                if ((object.ReferenceEquals(this.lRcvDatosField, value) != true)) {
                    this.lRcvDatosField = value;
                    this.RaisePropertyChanged("lRcvDatos");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CSRcv15Obtener", Namespace="http://schemas.datacontract.org/2004/07/ExternosNegociosCoreSoat.Modulos.ReporteC" +
        "ierreVentas.ClasesSalida")]
    [System.SerializableAttribute()]
    public partial class CSRcv15Obtener : TestFlujoWebServiceSOAT.wsReporteCierreVentas.CSRcv {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestFlujoWebServiceSOAT.wsReporteCierreVentas.CRcvDatosIniciales oRcvDatosInicialesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestFlujoWebServiceSOAT.wsReporteCierreVentas.CRcvDatosIniciales oRcvDatosIniciales {
            get {
                return this.oRcvDatosInicialesField;
            }
            set {
                if ((object.ReferenceEquals(this.oRcvDatosInicialesField, value) != true)) {
                    this.oRcvDatosInicialesField = value;
                    this.RaisePropertyChanged("oRcvDatosIniciales");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CSRcv16Revertir", Namespace="http://schemas.datacontract.org/2004/07/ExternosNegociosCoreSoat.Modulos.ReporteC" +
        "ierreVentas.ClasesSalida")]
    [System.SerializableAttribute()]
    public partial class CSRcv16Revertir : TestFlujoWebServiceSOAT.wsReporteCierreVentas.CSRcv {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RcvSecuencialField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RcvSecuencial {
            get {
                return this.RcvSecuencialField;
            }
            set {
                if ((this.RcvSecuencialField.Equals(value) != true)) {
                    this.RcvSecuencialField = value;
                    this.RaisePropertyChanged("RcvSecuencial");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CSRcv10ActualizarFechaLiquidacion", Namespace="http://schemas.datacontract.org/2004/07/ExternosNegociosCoreSoat.Modulos.ReporteC" +
        "ierreVentas.ClasesSalida")]
    [System.SerializableAttribute()]
    public partial class CSRcv10ActualizarFechaLiquidacion : TestFlujoWebServiceSOAT.wsReporteCierreVentas.CSRcv {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CantidadActualizadosField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CantidadActualizados {
            get {
                return this.CantidadActualizadosField;
            }
            set {
                if ((this.CantidadActualizadosField.Equals(value) != true)) {
                    this.CantidadActualizadosField = value;
                    this.RaisePropertyChanged("CantidadActualizados");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CRcvDatosVentas", Namespace="http://schemas.datacontract.org/2004/07/BibliotecaCoreSoat.Modulos.ReporteCierreV" +
        "entas.Entidades")]
    [System.SerializableAttribute()]
    public partial class CRcvDatosVentas : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RcvCantidadSoatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RcvCantidadSoatAnuladosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RcvCantidadSoatRevertidosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RcvCantidadSoatValidosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RcvFormularioImporteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestFlujoWebServiceSOAT.wsReporteCierreVentas.CSoatDatosVenta[] lSoatDatosVentaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RcvCantidadSoat {
            get {
                return this.RcvCantidadSoatField;
            }
            set {
                if ((this.RcvCantidadSoatField.Equals(value) != true)) {
                    this.RcvCantidadSoatField = value;
                    this.RaisePropertyChanged("RcvCantidadSoat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RcvCantidadSoatAnulados {
            get {
                return this.RcvCantidadSoatAnuladosField;
            }
            set {
                if ((this.RcvCantidadSoatAnuladosField.Equals(value) != true)) {
                    this.RcvCantidadSoatAnuladosField = value;
                    this.RaisePropertyChanged("RcvCantidadSoatAnulados");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RcvCantidadSoatRevertidos {
            get {
                return this.RcvCantidadSoatRevertidosField;
            }
            set {
                if ((this.RcvCantidadSoatRevertidosField.Equals(value) != true)) {
                    this.RcvCantidadSoatRevertidosField = value;
                    this.RaisePropertyChanged("RcvCantidadSoatRevertidos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RcvCantidadSoatValidos {
            get {
                return this.RcvCantidadSoatValidosField;
            }
            set {
                if ((this.RcvCantidadSoatValidosField.Equals(value) != true)) {
                    this.RcvCantidadSoatValidosField = value;
                    this.RaisePropertyChanged("RcvCantidadSoatValidos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RcvFormularioImporte {
            get {
                return this.RcvFormularioImporteField;
            }
            set {
                if ((this.RcvFormularioImporteField.Equals(value) != true)) {
                    this.RcvFormularioImporteField = value;
                    this.RaisePropertyChanged("RcvFormularioImporte");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestFlujoWebServiceSOAT.wsReporteCierreVentas.CSoatDatosVenta[] lSoatDatosVenta {
            get {
                return this.lSoatDatosVentaField;
            }
            set {
                if ((object.ReferenceEquals(this.lSoatDatosVentaField, value) != true)) {
                    this.lSoatDatosVentaField = value;
                    this.RaisePropertyChanged("lSoatDatosVenta");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CSoatDatosVenta", Namespace="http://schemas.datacontract.org/2004/07/ExternosAgenteServiciosCoreSoat.Modulos.V" +
        "entas.EntidadesSalida")]
    [System.SerializableAttribute()]
    public partial class CSoatDatosVenta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FactAutorizacionNumeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FactFechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FactNumeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal FactPrimaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SoatNroComprobanteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SoatTParGenericaEstadoFkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VehiPlacaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FactAutorizacionNumero {
            get {
                return this.FactAutorizacionNumeroField;
            }
            set {
                if ((object.ReferenceEquals(this.FactAutorizacionNumeroField, value) != true)) {
                    this.FactAutorizacionNumeroField = value;
                    this.RaisePropertyChanged("FactAutorizacionNumero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FactFecha {
            get {
                return this.FactFechaField;
            }
            set {
                if ((this.FactFechaField.Equals(value) != true)) {
                    this.FactFechaField = value;
                    this.RaisePropertyChanged("FactFecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FactNumero {
            get {
                return this.FactNumeroField;
            }
            set {
                if ((this.FactNumeroField.Equals(value) != true)) {
                    this.FactNumeroField = value;
                    this.RaisePropertyChanged("FactNumero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal FactPrima {
            get {
                return this.FactPrimaField;
            }
            set {
                if ((this.FactPrimaField.Equals(value) != true)) {
                    this.FactPrimaField = value;
                    this.RaisePropertyChanged("FactPrima");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SoatNroComprobante {
            get {
                return this.SoatNroComprobanteField;
            }
            set {
                if ((this.SoatNroComprobanteField.Equals(value) != true)) {
                    this.SoatNroComprobanteField = value;
                    this.RaisePropertyChanged("SoatNroComprobante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SoatTParGenericaEstadoFk {
            get {
                return this.SoatTParGenericaEstadoFkField;
            }
            set {
                if ((this.SoatTParGenericaEstadoFkField.Equals(value) != true)) {
                    this.SoatTParGenericaEstadoFkField = value;
                    this.RaisePropertyChanged("SoatTParGenericaEstadoFk");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VehiPlaca {
            get {
                return this.VehiPlacaField;
            }
            set {
                if ((object.ReferenceEquals(this.VehiPlacaField, value) != true)) {
                    this.VehiPlacaField = value;
                    this.RaisePropertyChanged("VehiPlaca");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CRcvDatos", Namespace="http://schemas.datacontract.org/2004/07/BibliotecaCoreSoat.Modulos.ReporteCierreV" +
        "entas.Entidades")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestFlujoWebServiceSOAT.wsReporteCierreVentas.CRcvDatosIniciales))]
    public partial class CRcvDatos : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RcvCantidadSoatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RcvCantidadSoatAnuladosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RcvCantidadSoatRevertidosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RcvCantidadSoatValidosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool RcvEstadoRemitidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime RcvFormularioFechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal RcvFormularioImporteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RcvSecuencialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RcvTParGenericaEstadoFkField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RcvCantidadSoat {
            get {
                return this.RcvCantidadSoatField;
            }
            set {
                if ((this.RcvCantidadSoatField.Equals(value) != true)) {
                    this.RcvCantidadSoatField = value;
                    this.RaisePropertyChanged("RcvCantidadSoat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RcvCantidadSoatAnulados {
            get {
                return this.RcvCantidadSoatAnuladosField;
            }
            set {
                if ((this.RcvCantidadSoatAnuladosField.Equals(value) != true)) {
                    this.RcvCantidadSoatAnuladosField = value;
                    this.RaisePropertyChanged("RcvCantidadSoatAnulados");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RcvCantidadSoatRevertidos {
            get {
                return this.RcvCantidadSoatRevertidosField;
            }
            set {
                if ((this.RcvCantidadSoatRevertidosField.Equals(value) != true)) {
                    this.RcvCantidadSoatRevertidosField = value;
                    this.RaisePropertyChanged("RcvCantidadSoatRevertidos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RcvCantidadSoatValidos {
            get {
                return this.RcvCantidadSoatValidosField;
            }
            set {
                if ((this.RcvCantidadSoatValidosField.Equals(value) != true)) {
                    this.RcvCantidadSoatValidosField = value;
                    this.RaisePropertyChanged("RcvCantidadSoatValidos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool RcvEstadoRemitido {
            get {
                return this.RcvEstadoRemitidoField;
            }
            set {
                if ((this.RcvEstadoRemitidoField.Equals(value) != true)) {
                    this.RcvEstadoRemitidoField = value;
                    this.RaisePropertyChanged("RcvEstadoRemitido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime RcvFormularioFecha {
            get {
                return this.RcvFormularioFechaField;
            }
            set {
                if ((this.RcvFormularioFechaField.Equals(value) != true)) {
                    this.RcvFormularioFechaField = value;
                    this.RaisePropertyChanged("RcvFormularioFecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal RcvFormularioImporte {
            get {
                return this.RcvFormularioImporteField;
            }
            set {
                if ((this.RcvFormularioImporteField.Equals(value) != true)) {
                    this.RcvFormularioImporteField = value;
                    this.RaisePropertyChanged("RcvFormularioImporte");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RcvSecuencial {
            get {
                return this.RcvSecuencialField;
            }
            set {
                if ((this.RcvSecuencialField.Equals(value) != true)) {
                    this.RcvSecuencialField = value;
                    this.RaisePropertyChanged("RcvSecuencial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RcvTParGenericaEstadoFk {
            get {
                return this.RcvTParGenericaEstadoFkField;
            }
            set {
                if ((this.RcvTParGenericaEstadoFkField.Equals(value) != true)) {
                    this.RcvTParGenericaEstadoFkField = value;
                    this.RaisePropertyChanged("RcvTParGenericaEstadoFk");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CRcvDatosIniciales", Namespace="http://schemas.datacontract.org/2004/07/BibliotecaCoreSoat.Modulos.ReporteCierreV" +
        "entas.Entidades")]
    [System.SerializableAttribute()]
    public partial class CRcvDatosIniciales : TestFlujoWebServiceSOAT.wsReporteCierreVentas.CRcvDatos {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime RcvFechaElaboradoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RcvFechaElaboradoFormatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RcvFormularioFechaFormatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RcvFormularioNumeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RcvTIntermediarioFkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RcvTParGestionFkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RcvTParVentaCanalFkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RcvVentaVendedorField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime RcvFechaElaborado {
            get {
                return this.RcvFechaElaboradoField;
            }
            set {
                if ((this.RcvFechaElaboradoField.Equals(value) != true)) {
                    this.RcvFechaElaboradoField = value;
                    this.RaisePropertyChanged("RcvFechaElaborado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RcvFechaElaboradoFormat {
            get {
                return this.RcvFechaElaboradoFormatField;
            }
            set {
                if ((object.ReferenceEquals(this.RcvFechaElaboradoFormatField, value) != true)) {
                    this.RcvFechaElaboradoFormatField = value;
                    this.RaisePropertyChanged("RcvFechaElaboradoFormat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RcvFormularioFechaFormat {
            get {
                return this.RcvFormularioFechaFormatField;
            }
            set {
                if ((object.ReferenceEquals(this.RcvFormularioFechaFormatField, value) != true)) {
                    this.RcvFormularioFechaFormatField = value;
                    this.RaisePropertyChanged("RcvFormularioFechaFormat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RcvFormularioNumero {
            get {
                return this.RcvFormularioNumeroField;
            }
            set {
                if ((this.RcvFormularioNumeroField.Equals(value) != true)) {
                    this.RcvFormularioNumeroField = value;
                    this.RaisePropertyChanged("RcvFormularioNumero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RcvTIntermediarioFk {
            get {
                return this.RcvTIntermediarioFkField;
            }
            set {
                if ((this.RcvTIntermediarioFkField.Equals(value) != true)) {
                    this.RcvTIntermediarioFkField = value;
                    this.RaisePropertyChanged("RcvTIntermediarioFk");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RcvTParGestionFk {
            get {
                return this.RcvTParGestionFkField;
            }
            set {
                if ((this.RcvTParGestionFkField.Equals(value) != true)) {
                    this.RcvTParGestionFkField = value;
                    this.RaisePropertyChanged("RcvTParGestionFk");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RcvTParVentaCanalFk {
            get {
                return this.RcvTParVentaCanalFkField;
            }
            set {
                if ((this.RcvTParVentaCanalFkField.Equals(value) != true)) {
                    this.RcvTParVentaCanalFkField = value;
                    this.RaisePropertyChanged("RcvTParVentaCanalFk");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RcvVentaVendedor {
            get {
                return this.RcvVentaVendedorField;
            }
            set {
                if ((object.ReferenceEquals(this.RcvVentaVendedorField, value) != true)) {
                    this.RcvVentaVendedorField = value;
                    this.RaisePropertyChanged("RcvVentaVendedor");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsReporteCierreVentas.IwsReporteCierreVentas")]
    public interface IwsReporteCierreVentas {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsReporteCierreVentas/Rcv10ActualizarFechaLiquidacion", ReplyAction="http://tempuri.org/IwsReporteCierreVentas/Rcv10ActualizarFechaLiquidacionResponse" +
            "")]
        TestFlujoWebServiceSOAT.wsReporteCierreVentas.CSRcv10ActualizarFechaLiquidacion Rcv10ActualizarFechaLiquidacion(TestFlujoWebServiceSOAT.wsReporteCierreVentas.CERcv10ActualizarFechaLiquidacion oERcv10ActualizarFechaLiquidacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsReporteCierreVentas/Rcv11ListarVentas", ReplyAction="http://tempuri.org/IwsReporteCierreVentas/Rcv11ListarVentasResponse")]
        TestFlujoWebServiceSOAT.wsReporteCierreVentas.CSRcv11ListarVentas Rcv11ListarVentas(TestFlujoWebServiceSOAT.wsReporteCierreVentas.CERcv11ListarVentas oERcv11ListarVentas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsReporteCierreVentas/Rcv12Efectivizar", ReplyAction="http://tempuri.org/IwsReporteCierreVentas/Rcv12EfectivizarResponse")]
        TestFlujoWebServiceSOAT.wsReporteCierreVentas.CSRcv12Efectivizar Rcv12Efectivizar(TestFlujoWebServiceSOAT.wsReporteCierreVentas.CERcv12Efectivizar oERcv12Efectivizar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsReporteCierreVentas/Rcv13Remitir", ReplyAction="http://tempuri.org/IwsReporteCierreVentas/Rcv13RemitirResponse")]
        TestFlujoWebServiceSOAT.wsReporteCierreVentas.CSRcv13Remitir Rcv13Remitir(TestFlujoWebServiceSOAT.wsReporteCierreVentas.CERcv13Remitir oERcv13Remitir);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsReporteCierreVentas/Rcv14Listar", ReplyAction="http://tempuri.org/IwsReporteCierreVentas/Rcv14ListarResponse")]
        TestFlujoWebServiceSOAT.wsReporteCierreVentas.CSRcv14Listar Rcv14Listar(TestFlujoWebServiceSOAT.wsReporteCierreVentas.CERcv14Listar oERcv14Listar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsReporteCierreVentas/Rcv15Obtener", ReplyAction="http://tempuri.org/IwsReporteCierreVentas/Rcv15ObtenerResponse")]
        TestFlujoWebServiceSOAT.wsReporteCierreVentas.CSRcv15Obtener Rcv15Obtener(TestFlujoWebServiceSOAT.wsReporteCierreVentas.CERcv15Obtener oERcv15Obtener);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsReporteCierreVentas/Rcv16Revertir", ReplyAction="http://tempuri.org/IwsReporteCierreVentas/Rcv16RevertirResponse")]
        TestFlujoWebServiceSOAT.wsReporteCierreVentas.CSRcv16Revertir Rcv16Revertir(TestFlujoWebServiceSOAT.wsReporteCierreVentas.CERcv16Revertir oERcv16Revertir);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IwsReporteCierreVentasChannel : TestFlujoWebServiceSOAT.wsReporteCierreVentas.IwsReporteCierreVentas, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IwsReporteCierreVentasClient : System.ServiceModel.ClientBase<TestFlujoWebServiceSOAT.wsReporteCierreVentas.IwsReporteCierreVentas>, TestFlujoWebServiceSOAT.wsReporteCierreVentas.IwsReporteCierreVentas {
        
        public IwsReporteCierreVentasClient() {
        }
        
        public IwsReporteCierreVentasClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IwsReporteCierreVentasClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IwsReporteCierreVentasClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IwsReporteCierreVentasClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TestFlujoWebServiceSOAT.wsReporteCierreVentas.CSRcv10ActualizarFechaLiquidacion Rcv10ActualizarFechaLiquidacion(TestFlujoWebServiceSOAT.wsReporteCierreVentas.CERcv10ActualizarFechaLiquidacion oERcv10ActualizarFechaLiquidacion) {
            return base.Channel.Rcv10ActualizarFechaLiquidacion(oERcv10ActualizarFechaLiquidacion);
        }
        
        public TestFlujoWebServiceSOAT.wsReporteCierreVentas.CSRcv11ListarVentas Rcv11ListarVentas(TestFlujoWebServiceSOAT.wsReporteCierreVentas.CERcv11ListarVentas oERcv11ListarVentas) {
            return base.Channel.Rcv11ListarVentas(oERcv11ListarVentas);
        }
        
        public TestFlujoWebServiceSOAT.wsReporteCierreVentas.CSRcv12Efectivizar Rcv12Efectivizar(TestFlujoWebServiceSOAT.wsReporteCierreVentas.CERcv12Efectivizar oERcv12Efectivizar) {
            return base.Channel.Rcv12Efectivizar(oERcv12Efectivizar);
        }
        
        public TestFlujoWebServiceSOAT.wsReporteCierreVentas.CSRcv13Remitir Rcv13Remitir(TestFlujoWebServiceSOAT.wsReporteCierreVentas.CERcv13Remitir oERcv13Remitir) {
            return base.Channel.Rcv13Remitir(oERcv13Remitir);
        }
        
        public TestFlujoWebServiceSOAT.wsReporteCierreVentas.CSRcv14Listar Rcv14Listar(TestFlujoWebServiceSOAT.wsReporteCierreVentas.CERcv14Listar oERcv14Listar) {
            return base.Channel.Rcv14Listar(oERcv14Listar);
        }
        
        public TestFlujoWebServiceSOAT.wsReporteCierreVentas.CSRcv15Obtener Rcv15Obtener(TestFlujoWebServiceSOAT.wsReporteCierreVentas.CERcv15Obtener oERcv15Obtener) {
            return base.Channel.Rcv15Obtener(oERcv15Obtener);
        }
        
        public TestFlujoWebServiceSOAT.wsReporteCierreVentas.CSRcv16Revertir Rcv16Revertir(TestFlujoWebServiceSOAT.wsReporteCierreVentas.CERcv16Revertir oERcv16Revertir) {
            return base.Channel.Rcv16Revertir(oERcv16Revertir);
        }
    }
}
