//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18034
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cerberus.ATC.GatewayV2Service.wsSeguridad {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CEModulos", Namespace="http://schemas.datacontract.org/2004/07/ExternosNegociosCoreSoat.Modulos.ClasesBa" +
        "se")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Cerberus.ATC.GatewayV2Service.wsSeguridad.CESeg))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Cerberus.ATC.GatewayV2Service.wsSeguridad.CESeg02CambiarContrasenia))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Cerberus.ATC.GatewayV2Service.wsSeguridad.CESeg01Autenticacion))]
    public partial class CEModulos : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SoatTIntermediarioFkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SoatTIntermediarioFk {
            get {
                return this.SoatTIntermediarioFkField;
            }
            set {
                if ((this.SoatTIntermediarioFkField.Equals(value) != true)) {
                    this.SoatTIntermediarioFkField = value;
                    this.RaisePropertyChanged("SoatTIntermediarioFk");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usuario {
            get {
                return this.UsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioField, value) != true)) {
                    this.UsuarioField = value;
                    this.RaisePropertyChanged("Usuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CESeg", Namespace="http://schemas.datacontract.org/2004/07/ExternosNegociosCoreSoat.Modulos.Segurida" +
        "d.ClasesEntrada")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Cerberus.ATC.GatewayV2Service.wsSeguridad.CESeg02CambiarContrasenia))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Cerberus.ATC.GatewayV2Service.wsSeguridad.CESeg01Autenticacion))]
    public partial class CESeg : Cerberus.ATC.GatewayV2Service.wsSeguridad.CEModulos {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CESeg02CambiarContrasenia", Namespace="http://schemas.datacontract.org/2004/07/ExternosNegociosCoreSoat.Modulos.Segurida" +
        "d.ClasesEntrada")]
    [System.SerializableAttribute()]
    public partial class CESeg02CambiarContrasenia : Cerberus.ATC.GatewayV2Service.wsSeguridad.CESeg {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContraseniaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContraseniaNuevaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IpField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contrasenia {
            get {
                return this.ContraseniaField;
            }
            set {
                if ((object.ReferenceEquals(this.ContraseniaField, value) != true)) {
                    this.ContraseniaField = value;
                    this.RaisePropertyChanged("Contrasenia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContraseniaNueva {
            get {
                return this.ContraseniaNuevaField;
            }
            set {
                if ((object.ReferenceEquals(this.ContraseniaNuevaField, value) != true)) {
                    this.ContraseniaNuevaField = value;
                    this.RaisePropertyChanged("ContraseniaNueva");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ip {
            get {
                return this.IpField;
            }
            set {
                if ((object.ReferenceEquals(this.IpField, value) != true)) {
                    this.IpField = value;
                    this.RaisePropertyChanged("Ip");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CESeg01Autenticacion", Namespace="http://schemas.datacontract.org/2004/07/ExternosNegociosCoreSoat.Modulos.Segurida" +
        "d.ClasesEntrada")]
    [System.SerializableAttribute()]
    public partial class CESeg01Autenticacion : Cerberus.ATC.GatewayV2Service.wsSeguridad.CESeg {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContraseniaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IpField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contrasenia {
            get {
                return this.ContraseniaField;
            }
            set {
                if ((object.ReferenceEquals(this.ContraseniaField, value) != true)) {
                    this.ContraseniaField = value;
                    this.RaisePropertyChanged("Contrasenia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ip {
            get {
                return this.IpField;
            }
            set {
                if ((object.ReferenceEquals(this.IpField, value) != true)) {
                    this.IpField = value;
                    this.RaisePropertyChanged("Ip");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CSModulos", Namespace="http://schemas.datacontract.org/2004/07/ExternosNegociosCoreSoat.Modulos.ClasesBa" +
        "se")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Cerberus.ATC.GatewayV2Service.wsSeguridad.CSSeg))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Cerberus.ATC.GatewayV2Service.wsSeguridad.CSSeg02CambiarContrasenia))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Cerberus.ATC.GatewayV2Service.wsSeguridad.CSSeg01Autenticacion))]
    public partial class CSModulos : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoRetornoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ExitoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoRetorno {
            get {
                return this.CodigoRetornoField;
            }
            set {
                if ((this.CodigoRetornoField.Equals(value) != true)) {
                    this.CodigoRetornoField = value;
                    this.RaisePropertyChanged("CodigoRetorno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Exito {
            get {
                return this.ExitoField;
            }
            set {
                if ((this.ExitoField.Equals(value) != true)) {
                    this.ExitoField = value;
                    this.RaisePropertyChanged("Exito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CSSeg", Namespace="http://schemas.datacontract.org/2004/07/ExternosNegociosCoreSoat.Modulos.Segurida" +
        "d.ClasesSalida")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Cerberus.ATC.GatewayV2Service.wsSeguridad.CSSeg02CambiarContrasenia))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Cerberus.ATC.GatewayV2Service.wsSeguridad.CSSeg01Autenticacion))]
    public partial class CSSeg : Cerberus.ATC.GatewayV2Service.wsSeguridad.CSModulos {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CSSeg02CambiarContrasenia", Namespace="http://schemas.datacontract.org/2004/07/ExternosNegociosCoreSoat.Modulos.Segurida" +
        "d.ClasesSalida")]
    [System.SerializableAttribute()]
    public partial class CSSeg02CambiarContrasenia : Cerberus.ATC.GatewayV2Service.wsSeguridad.CSSeg {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CSSeg01Autenticacion", Namespace="http://schemas.datacontract.org/2004/07/ExternosNegociosCoreSoat.Modulos.Segurida" +
        "d.ClasesSalida")]
    [System.SerializableAttribute()]
    public partial class CSSeg01Autenticacion : Cerberus.ATC.GatewayV2Service.wsSeguridad.CSSeg {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SeguridadTokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Cerberus.ATC.GatewayV2Service.wsSeguridad.CTransUsuarioDatos oTransUsuarioDatosField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SeguridadToken {
            get {
                return this.SeguridadTokenField;
            }
            set {
                if ((this.SeguridadTokenField.Equals(value) != true)) {
                    this.SeguridadTokenField = value;
                    this.RaisePropertyChanged("SeguridadToken");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Cerberus.ATC.GatewayV2Service.wsSeguridad.CTransUsuarioDatos oTransUsuarioDatos {
            get {
                return this.oTransUsuarioDatosField;
            }
            set {
                if ((object.ReferenceEquals(this.oTransUsuarioDatosField, value) != true)) {
                    this.oTransUsuarioDatosField = value;
                    this.RaisePropertyChanged("oTransUsuarioDatos");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CTransUsuarioDatos", Namespace="http://schemas.datacontract.org/2004/07/UVNetTransversal.AgenteServicios.Segurida" +
        "d.UsuariosInternos.EntidadesSalida")]
    [System.SerializableAttribute()]
    public partial class CTransUsuarioDatos : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ContratoSecuencialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmpleadoApCasadaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmpleadoApMaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmpleadoApPaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmpleadoCargoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmpleadoCiudadResidenciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmpleadoDireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmpleadoDocuentoNroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmpleadoDocumentoCompletoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmpleadoDocumentoExtensionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmpleadoDocumentoTipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmpleadoNombreAltField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmpleadoNombreCompletoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmpleadoNombrePrimField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmpleadoNombreSegField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EmpleadoSecuencialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmpleadoUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EmpleadoUsuarioADField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EstadoEmpleadoActivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SucursalCiudadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SucursalCodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SucursalDepartamentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SucursalDireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SucursalIdDepartamentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SucursalNombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SuperiorCargoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SuperiorNombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SuperiorSecuencialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SuperiorUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SuperiorUsuarioADField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Cerberus.ATC.GatewayV2Service.wsSeguridad.CRol[] lRolField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ContratoSecuencial {
            get {
                return this.ContratoSecuencialField;
            }
            set {
                if ((this.ContratoSecuencialField.Equals(value) != true)) {
                    this.ContratoSecuencialField = value;
                    this.RaisePropertyChanged("ContratoSecuencial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmpleadoApCasada {
            get {
                return this.EmpleadoApCasadaField;
            }
            set {
                if ((object.ReferenceEquals(this.EmpleadoApCasadaField, value) != true)) {
                    this.EmpleadoApCasadaField = value;
                    this.RaisePropertyChanged("EmpleadoApCasada");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmpleadoApMaterno {
            get {
                return this.EmpleadoApMaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.EmpleadoApMaternoField, value) != true)) {
                    this.EmpleadoApMaternoField = value;
                    this.RaisePropertyChanged("EmpleadoApMaterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmpleadoApPaterno {
            get {
                return this.EmpleadoApPaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.EmpleadoApPaternoField, value) != true)) {
                    this.EmpleadoApPaternoField = value;
                    this.RaisePropertyChanged("EmpleadoApPaterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmpleadoCargo {
            get {
                return this.EmpleadoCargoField;
            }
            set {
                if ((object.ReferenceEquals(this.EmpleadoCargoField, value) != true)) {
                    this.EmpleadoCargoField = value;
                    this.RaisePropertyChanged("EmpleadoCargo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmpleadoCiudadResidencia {
            get {
                return this.EmpleadoCiudadResidenciaField;
            }
            set {
                if ((object.ReferenceEquals(this.EmpleadoCiudadResidenciaField, value) != true)) {
                    this.EmpleadoCiudadResidenciaField = value;
                    this.RaisePropertyChanged("EmpleadoCiudadResidencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmpleadoDireccion {
            get {
                return this.EmpleadoDireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.EmpleadoDireccionField, value) != true)) {
                    this.EmpleadoDireccionField = value;
                    this.RaisePropertyChanged("EmpleadoDireccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmpleadoDocuentoNro {
            get {
                return this.EmpleadoDocuentoNroField;
            }
            set {
                if ((object.ReferenceEquals(this.EmpleadoDocuentoNroField, value) != true)) {
                    this.EmpleadoDocuentoNroField = value;
                    this.RaisePropertyChanged("EmpleadoDocuentoNro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmpleadoDocumentoCompleto {
            get {
                return this.EmpleadoDocumentoCompletoField;
            }
            set {
                if ((object.ReferenceEquals(this.EmpleadoDocumentoCompletoField, value) != true)) {
                    this.EmpleadoDocumentoCompletoField = value;
                    this.RaisePropertyChanged("EmpleadoDocumentoCompleto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmpleadoDocumentoExtension {
            get {
                return this.EmpleadoDocumentoExtensionField;
            }
            set {
                if ((object.ReferenceEquals(this.EmpleadoDocumentoExtensionField, value) != true)) {
                    this.EmpleadoDocumentoExtensionField = value;
                    this.RaisePropertyChanged("EmpleadoDocumentoExtension");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmpleadoDocumentoTipo {
            get {
                return this.EmpleadoDocumentoTipoField;
            }
            set {
                if ((object.ReferenceEquals(this.EmpleadoDocumentoTipoField, value) != true)) {
                    this.EmpleadoDocumentoTipoField = value;
                    this.RaisePropertyChanged("EmpleadoDocumentoTipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmpleadoNombreAlt {
            get {
                return this.EmpleadoNombreAltField;
            }
            set {
                if ((object.ReferenceEquals(this.EmpleadoNombreAltField, value) != true)) {
                    this.EmpleadoNombreAltField = value;
                    this.RaisePropertyChanged("EmpleadoNombreAlt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmpleadoNombreCompleto {
            get {
                return this.EmpleadoNombreCompletoField;
            }
            set {
                if ((object.ReferenceEquals(this.EmpleadoNombreCompletoField, value) != true)) {
                    this.EmpleadoNombreCompletoField = value;
                    this.RaisePropertyChanged("EmpleadoNombreCompleto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmpleadoNombrePrim {
            get {
                return this.EmpleadoNombrePrimField;
            }
            set {
                if ((object.ReferenceEquals(this.EmpleadoNombrePrimField, value) != true)) {
                    this.EmpleadoNombrePrimField = value;
                    this.RaisePropertyChanged("EmpleadoNombrePrim");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmpleadoNombreSeg {
            get {
                return this.EmpleadoNombreSegField;
            }
            set {
                if ((object.ReferenceEquals(this.EmpleadoNombreSegField, value) != true)) {
                    this.EmpleadoNombreSegField = value;
                    this.RaisePropertyChanged("EmpleadoNombreSeg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EmpleadoSecuencial {
            get {
                return this.EmpleadoSecuencialField;
            }
            set {
                if ((this.EmpleadoSecuencialField.Equals(value) != true)) {
                    this.EmpleadoSecuencialField = value;
                    this.RaisePropertyChanged("EmpleadoSecuencial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmpleadoUsuario {
            get {
                return this.EmpleadoUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.EmpleadoUsuarioField, value) != true)) {
                    this.EmpleadoUsuarioField = value;
                    this.RaisePropertyChanged("EmpleadoUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EmpleadoUsuarioAD {
            get {
                return this.EmpleadoUsuarioADField;
            }
            set {
                if ((this.EmpleadoUsuarioADField.Equals(value) != true)) {
                    this.EmpleadoUsuarioADField = value;
                    this.RaisePropertyChanged("EmpleadoUsuarioAD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EstadoEmpleadoActivo {
            get {
                return this.EstadoEmpleadoActivoField;
            }
            set {
                if ((this.EstadoEmpleadoActivoField.Equals(value) != true)) {
                    this.EstadoEmpleadoActivoField = value;
                    this.RaisePropertyChanged("EstadoEmpleadoActivo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SucursalCiudad {
            get {
                return this.SucursalCiudadField;
            }
            set {
                if ((object.ReferenceEquals(this.SucursalCiudadField, value) != true)) {
                    this.SucursalCiudadField = value;
                    this.RaisePropertyChanged("SucursalCiudad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SucursalCodigo {
            get {
                return this.SucursalCodigoField;
            }
            set {
                if ((this.SucursalCodigoField.Equals(value) != true)) {
                    this.SucursalCodigoField = value;
                    this.RaisePropertyChanged("SucursalCodigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SucursalDepartamento {
            get {
                return this.SucursalDepartamentoField;
            }
            set {
                if ((object.ReferenceEquals(this.SucursalDepartamentoField, value) != true)) {
                    this.SucursalDepartamentoField = value;
                    this.RaisePropertyChanged("SucursalDepartamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SucursalDireccion {
            get {
                return this.SucursalDireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.SucursalDireccionField, value) != true)) {
                    this.SucursalDireccionField = value;
                    this.RaisePropertyChanged("SucursalDireccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SucursalIdDepartamento {
            get {
                return this.SucursalIdDepartamentoField;
            }
            set {
                if ((object.ReferenceEquals(this.SucursalIdDepartamentoField, value) != true)) {
                    this.SucursalIdDepartamentoField = value;
                    this.RaisePropertyChanged("SucursalIdDepartamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SucursalNombre {
            get {
                return this.SucursalNombreField;
            }
            set {
                if ((object.ReferenceEquals(this.SucursalNombreField, value) != true)) {
                    this.SucursalNombreField = value;
                    this.RaisePropertyChanged("SucursalNombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SuperiorCargo {
            get {
                return this.SuperiorCargoField;
            }
            set {
                if ((object.ReferenceEquals(this.SuperiorCargoField, value) != true)) {
                    this.SuperiorCargoField = value;
                    this.RaisePropertyChanged("SuperiorCargo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SuperiorNombre {
            get {
                return this.SuperiorNombreField;
            }
            set {
                if ((object.ReferenceEquals(this.SuperiorNombreField, value) != true)) {
                    this.SuperiorNombreField = value;
                    this.RaisePropertyChanged("SuperiorNombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SuperiorSecuencial {
            get {
                return this.SuperiorSecuencialField;
            }
            set {
                if ((this.SuperiorSecuencialField.Equals(value) != true)) {
                    this.SuperiorSecuencialField = value;
                    this.RaisePropertyChanged("SuperiorSecuencial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SuperiorUsuario {
            get {
                return this.SuperiorUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.SuperiorUsuarioField, value) != true)) {
                    this.SuperiorUsuarioField = value;
                    this.RaisePropertyChanged("SuperiorUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SuperiorUsuarioAD {
            get {
                return this.SuperiorUsuarioADField;
            }
            set {
                if ((object.ReferenceEquals(this.SuperiorUsuarioADField, value) != true)) {
                    this.SuperiorUsuarioADField = value;
                    this.RaisePropertyChanged("SuperiorUsuarioAD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Cerberus.ATC.GatewayV2Service.wsSeguridad.CRol[] lRol {
            get {
                return this.lRolField;
            }
            set {
                if ((object.ReferenceEquals(this.lRolField, value) != true)) {
                    this.lRolField = value;
                    this.RaisePropertyChanged("lRol");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CRol", Namespace="http://schemas.datacontract.org/2004/07/UVNetTransversal.AgenteServicios.Segurida" +
        "d.UsuariosInternos.EntidadesSalida")]
    [System.SerializableAttribute()]
    public partial class CRol : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RolDescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RolIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RolSistemasField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RolDescripcion {
            get {
                return this.RolDescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.RolDescripcionField, value) != true)) {
                    this.RolDescripcionField = value;
                    this.RaisePropertyChanged("RolDescripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RolId {
            get {
                return this.RolIdField;
            }
            set {
                if ((this.RolIdField.Equals(value) != true)) {
                    this.RolIdField = value;
                    this.RaisePropertyChanged("RolId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RolSistemas {
            get {
                return this.RolSistemasField;
            }
            set {
                if ((object.ReferenceEquals(this.RolSistemasField, value) != true)) {
                    this.RolSistemasField = value;
                    this.RaisePropertyChanged("RolSistemas");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsSeguridad.IwsSeguridad")]
    public interface IwsSeguridad {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsSeguridad/Seg01Autenticacion", ReplyAction="http://tempuri.org/IwsSeguridad/Seg01AutenticacionResponse")]
        Cerberus.ATC.GatewayV2Service.wsSeguridad.CSSeg01Autenticacion Seg01Autenticacion(Cerberus.ATC.GatewayV2Service.wsSeguridad.CESeg01Autenticacion oESeg01Autenticacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsSeguridad/Seg02CambiarContrasenia", ReplyAction="http://tempuri.org/IwsSeguridad/Seg02CambiarContraseniaResponse")]
        Cerberus.ATC.GatewayV2Service.wsSeguridad.CSSeg02CambiarContrasenia Seg02CambiarContrasenia(Cerberus.ATC.GatewayV2Service.wsSeguridad.CESeg02CambiarContrasenia oESeg02CambiarContrasenia);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IwsSeguridadChannel : Cerberus.ATC.GatewayV2Service.wsSeguridad.IwsSeguridad, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IwsSeguridadClient : System.ServiceModel.ClientBase<Cerberus.ATC.GatewayV2Service.wsSeguridad.IwsSeguridad>, Cerberus.ATC.GatewayV2Service.wsSeguridad.IwsSeguridad {
        
        public IwsSeguridadClient() {
        }
        
        public IwsSeguridadClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IwsSeguridadClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IwsSeguridadClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IwsSeguridadClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Cerberus.ATC.GatewayV2Service.wsSeguridad.CSSeg01Autenticacion Seg01Autenticacion(Cerberus.ATC.GatewayV2Service.wsSeguridad.CESeg01Autenticacion oESeg01Autenticacion) {
            return base.Channel.Seg01Autenticacion(oESeg01Autenticacion);
        }
        
        public Cerberus.ATC.GatewayV2Service.wsSeguridad.CSSeg02CambiarContrasenia Seg02CambiarContrasenia(Cerberus.ATC.GatewayV2Service.wsSeguridad.CESeg02CambiarContrasenia oESeg02CambiarContrasenia) {
            return base.Channel.Seg02CambiarContrasenia(oESeg02CambiarContrasenia);
        }
    }
}
